version: '3'
services:
#############################################      
#              SPARK CLUSTER                #
#############################################
  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - shared_data:/spark
      - ./data:/data
  spark-worker-1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - shared_data:/spark
      - ./data:/data
  spark-worker-2:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - shared_data:/spark
      - ./data:/data
#############################################
#               ZEPPELIN                    #
#############################################
  zeppelin:
    image: apache/zeppelin:0.10.0
    ports:
      - "8080:8080"
    volumes:
      - shared_data:/zeppelin/spark
      - ./notebooks:/opt/zeppelin/notebook
      - ./data:/data
    environment:
      - "MASTER=spark://spark-master:7077"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/zeppelin/spark"
      - "PYSPARK_PYTHON=python3"
      - "PYSPARK_DRIVER_PYTHON=python3"

volumes:
  shared_data: